---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ark.yadon3141.com
  resources:
  - arkclusters
  - arkservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ark.yadon3141.com
  resources:
  - arkclusters/finalizers
  - arkservers/finalizers
  verbs:
  - update
- apiGroups:
  - ark.yadon3141.com
  resources:
  - arkclusters/status
  - arkservers/status
  verbs:
  - get
  - patch
  - update
